/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "ece61dc84aadb4c522fd7aed67bbcdcd1db4f7b9"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
